/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package senha.view.totem;

import java.util.logging.Level;
import java.util.logging.Logger;
import senha.model.SenhaAtendimento;
import senha.control.SenhaAtendimentoDAO;
import senha.model.SenhaCaixa;
import senha.control.SenhaCaixaDAO;
import senha.model.SenhaGerencia;
import senha.control.SenhaGerenciaDAO;
import senha.control.AtualizadorHorario;
import senha.model.Setor;
import senha.model.SiglaSetor;
import senha.model.StatusSenha;
import senha.model.TipoAtendimento;

/**
 *
 * @author welti_000
 */
public class TelaSetorConvencional extends javax.swing.JFrame implements Runnable {

    Thread threadVoltar;
    boolean executando;

    String data;
    String hora;

    /**
     * Creates new form TelaSetor
     */
    public TelaSetorConvencional() {
        this.voltar();
        initComponents();
        AtualizadorHorario horario = new AtualizadorHorario();
        jLData.setText(horario.dataSistema());
        AtualizadorHorario.horaSistema(jLHora);

        data = horario.dataSistema();
        hora = horario.horaAtualSistema();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLData = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLHora = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 73, 78));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/senha/img/caixaNor.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/senha/img/atendimentoNor.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/senha/img/gerenciaNor.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/senha/img/voltarNor.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jPanel2.setBackground(new java.awt.Color(191, 215, 62));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/senha/img/data.png"))); // NOI18N

        jLData.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLData.setText("05/07/2015");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/senha/img/relogio.png"))); // NOI18N

        jLHora.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLHora.setText("08:57:20");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLHora)
                .addGap(121, 121, 121))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLHora)
                            .addComponent(jLData))))
                .addGap(11, 11, 11))
        );

        jLabel1.setBackground(new java.awt.Color(191, 215, 62));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOQUE NA OPÇÃO DESEJADA");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.cancelar();
        
        TelaImpresao tela = new TelaImpresao(this.gerandoSenhaCaixaNormal());
        tela.setVisible(true);
        this.setVisible(false);
         this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.cancelar();
       
        TelaImpresao tela = new TelaImpresao(this.gerandoSenhaAtendimentoNormal());
        tela.setVisible(true);
        this.setVisible(false);
         this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.cancelar();
        
        TelaImpresao tela = new TelaImpresao(this.gerandoSenhaGerenciaNormal());
        tela.setVisible(true);
        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.cancelar();
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSetorConvencional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSetorConvencional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSetorConvencional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSetorConvencional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaSetorConvencional().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLData;
    private javax.swing.JLabel jLHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    public SenhaCaixa gerandoSenhaCaixaNormal() {
        SenhaCaixaDAO dao = new SenhaCaixaDAO();
        SenhaCaixa senhacaixa = new SenhaCaixa();
        if (dao.selectSenhaCaixaNormal().isEmpty()) {
            senhacaixa.setNumeroSenha(1);
            senhacaixa.setSetor(Setor.CAIXA);
            senhacaixa.setTipoAtendimento(TipoAtendimento.CONVENCIONAL);
            senhacaixa.setSigla(SiglaSetor.CC);
            senhacaixa.setDataSenha(data);
            senhacaixa.setHoraSenha(hora);
            senhacaixa.setStatusSenha(StatusSenha.AGUARDANDO);

            dao.inserirSenhaCaixa(senhacaixa);
     
        } else {
            SenhaCaixa ultimaSenha = dao.selectSenhaCaixaNormal().get(dao.selectSenhaCaixaNormal().size() - 1);
            int senha = ultimaSenha.getNumeroSenha();
            senhacaixa.setNumeroSenha(senha + 1);
            senhacaixa.setSetor(Setor.CAIXA);
            senhacaixa.setTipoAtendimento(TipoAtendimento.CONVENCIONAL);
            senhacaixa.setSigla(SiglaSetor.CC);
            senhacaixa.setDataSenha(data);
            senhacaixa.setHoraSenha(hora);
            senhacaixa.setStatusSenha(StatusSenha.AGUARDANDO);
           
            dao.inserirSenhaCaixa(senhacaixa);
            
            

        }
        return senhacaixa;
    }

    public SenhaAtendimento gerandoSenhaAtendimentoNormal() {
        SenhaAtendimentoDAO dao = new SenhaAtendimentoDAO();
        SenhaAtendimento senhaAtendimento = new SenhaAtendimento();
        if (dao.selectSenhaAtendimentoNormal().isEmpty()) {
            senhaAtendimento.setNumeroSenha(1);
            senhaAtendimento.setSetor(Setor.ATENDIMENTO);
            senhaAtendimento.setTipoAtendimento(TipoAtendimento.CONVENCIONAL);
            senhaAtendimento.setSigla(SiglaSetor.AC);
            senhaAtendimento.setDataSenha(data);
            senhaAtendimento.setHoraSenha(hora);
            senhaAtendimento.setStatusSenha(StatusSenha.AGUARDANDO);

            dao.inserirSenhaAtendimento(senhaAtendimento);
        } else {
            SenhaAtendimento ultimaSenha = dao.selectSenhaAtendimentoNormal().get(dao.selectSenhaAtendimentoNormal().size() - 1);
            int senha = ultimaSenha.getNumeroSenha();

            senhaAtendimento.setNumeroSenha(senha + 1);
            senhaAtendimento.setSetor(Setor.ATENDIMENTO);
            senhaAtendimento.setTipoAtendimento(TipoAtendimento.CONVENCIONAL);
            senhaAtendimento.setSigla(SiglaSetor.AC);
            senhaAtendimento.setDataSenha(data);
            senhaAtendimento.setHoraSenha(hora);
            senhaAtendimento.setStatusSenha(StatusSenha.AGUARDANDO);

            dao.inserirSenhaAtendimento(senhaAtendimento);

        }
        return senhaAtendimento;
    }

    public SenhaGerencia gerandoSenhaGerenciaNormal() {
        SenhaGerenciaDAO dao = new SenhaGerenciaDAO();
        SenhaGerencia senhaGerencia = new SenhaGerencia();
        if (dao.selectSenhaGerenciaNormal().isEmpty()) {
            senhaGerencia.setNumeroSenha(1);
            senhaGerencia.setSetor(Setor.GERENCIA);
            senhaGerencia.setTipoAtendimento(TipoAtendimento.CONVENCIONAL);
            senhaGerencia.setSigla(SiglaSetor.GC);
            senhaGerencia.setDataSenha(data);
            senhaGerencia.setHoraSenha(hora);
            senhaGerencia.setStatusSenha(StatusSenha.AGUARDANDO);

            dao.inserirSenhaGerencia(senhaGerencia);
        } else {
            SenhaGerencia ultimaSenha = dao.selectSenhaGerenciaNormal().get(dao.selectSenhaGerenciaNormal().size() - 1);
            int senha = ultimaSenha.getNumeroSenha();

            senhaGerencia.setNumeroSenha(senha + 1);
            senhaGerencia.setSetor(Setor.GERENCIA);
            senhaGerencia.setTipoAtendimento(TipoAtendimento.CONVENCIONAL);
            senhaGerencia.setSigla(SiglaSetor.GC);
            senhaGerencia.setDataSenha(data);
            senhaGerencia.setHoraSenha(hora);
            senhaGerencia.setStatusSenha(StatusSenha.AGUARDANDO);

            dao.inserirSenhaGerencia(senhaGerencia);

        }
        return senhaGerencia;
    }

    @Override
    public void run() {
        int i = 0;
        while (i < 10 && executando) {
            i++;
            try {
                Thread.sleep(1000);

            } catch (InterruptedException ex) {
                Logger.getLogger(TelaTotem.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (executando) {
            this.setVisible(false);
             this.dispose();
        }

    }

    private void voltar() {
        executando = true;
        threadVoltar = new Thread(this);
        threadVoltar.start();

    }

    public void cancelar() {
        executando = false;
    }
}
